dist: trusty
language: C
os:
  - linux
  - osx

branches:
  only:
    - master

env:
  global:
    - secure: "IHICwP4oMbC6yzx9G4YIthU6ujpt0bJ4jOElN7ujs8xGODB7YQFlxIaBwLvCf8APjczUuarN1r0Vc/Ekyp8LVBVdI6oEK0ZyHkvXOsydtYAtKrK60iEZXLoMzqTR/DeZaLkQb/hh4tYLAfrzNs9ZZA6vU1rJUJdaNmxluM9kcF253tfxKZ7rZ8dveD+gwmfJYH47sNwvFiGVTmU6c9fDVVfE/R3c0aX3A4pI3oOAUMH6Vs/76ZdRh2knzLLDgcNiIDapJd1xlw8HFSyEbsfEgTLPl+9qeXyh8fU6kwU7tGKetdr60klrXChIdwqStOxNwp4ylto727oYtztj7zJxYWQxbXQwehH66Xj44KEfW9MEuBEbGCmlR/74vCTNnKVU6D857ZU7r0L43GTD9KfAqqHWKtdQJpoRZMkhRcFrZkHCG8GJJo+3swwXFWnPbqPDuGWnLaeg4dsFpcAhq4ujSFheJbJ+ilERGio8ksv+FndlImSsQVEHtErPyJlizE3y2QfdWfASpn5HYVJ5la0Vy5Tea0rPRymdtLQm3lCMX+qcAg9EQLFHsc52LsFUwnHrNu5WqzfCmN0b7kfT4SlEHVXOXtC6k5PYxAUBaHfyeVFspc4UN5ZTUmSj9Y2h47Oa5KV/DJRaNKalve3TYgysEvlnTqv6qJfqnbHO2Swl+GE="

addons:
  apt:
    packages:
      - doxygen
      - graphviz

script:
  - cmake .
  - git clone -b gh-pages https://git@github.com/NTAP/warpcore.git gh-pages
  - cd gh-pages
  - ls -la
  - git config --global push.default simple
  - git config user.name "Travis CI"
  - git config user.email "travis@travis-ci.org"
  - rm -rf ./*
  - touch .nojekyll
  - doxygen $TRAVIS_BUILD_DIR/doc/Doxyfile 2>&1 | tee doxygen.log
  - |
    if [ -d "html" ] && [ -f "html/index.html" ]; then
        mv html/* .
        git add --all
        git commit -m "Update doxygen documentation on branch gh-pages." \
            -m "Travis CI build ${TRAVIS_BUILD_NUMBER}." \
            -m "Commit: ${TRAVIS_COMMIT}."
        git push --force https://${GH_REPO_TOKEN}@github.com/NTAP/warpcore.git > /dev/null 2>&1
    fi
